[book]
authors = ["Ivan Vilata-i-Balaguer", "Dmitri Vitaliev", "Jenny Ryan"]
language = "es"
multilingual = false
src = "es"
title = "Censorship.no! Manual del Usuario"

[output.html]
git-repository-url = "https://github.com/censorship-no/ceno-docs"

[build]
build-dir = "es.book"
