[book]
authors = ["Ivan Vilata-i-Balaguer", "Dmitri Vitaliev", "Jenny Ryan"]
language = "my"
multilingual = false
src = "my.src"
title = "Censorship.no! သုံးစွဲသူ လက်စွဲ"

[output.html]
git-repository-url = "https://github.com/censorship-no/ceno-docs"

[build]
build-dir = "my.book"
